name: Run lighthouse CI When Push

on:
  push:
    branches:
      - main

jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Packages
        run: npm install && npm install -g @lhci/cli

      - name: Run LightHouse CI
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          NEXT_PUBLIC_NOTION_PAGE_ID: ${{ secrets.NOTION_PAGE_ID }}
          NEXT_PUBLIC_AWS_IMAGE_URL: ${{ secrets.NEXT_PUBLIC_AWS_IMAGE_URL }}
          NEXT_PUBLIC_LOCAL_URL: ${{ secrets.NEXT_PUBLIC_LOCAL_URL }}
          NEXT_PUBLIC_PRODUCT_URL: ${{ secrets.NEXT_PUBLIC_PRODUCT_URL }}
          NEXT_PUBLIC_NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          NEXT_PUBLIC_NOTION_KEY: ${{ secrets.NOTION_KEY }}
          NEXT_PUBLIC_NOTION_RESUME_ID: ${{ secrets.NOTION_RESUME_ID }}
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
          NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
          NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}
          NEXT_PUBLIC_FIREBASE_DATABASE: ${{ secrets.NEXT_PUBLIC_FIREBASE_DATABASE }}
          NEXT_PUBLIC_MEASUREMENT_ID : ${{secrets.NEXT_PUBLIC_MEASUREMENT_ID}}
        run: npm run lhci
